[package]
name = "prob054"
version = "0.1.0"
authors = ["Michael Hoang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euler_utils = { path = "../*utils" }
strum = "0.18.0"
strum_macros = "0.18.0"
