[package]
name = "euler_utils"
version = "0.1.0"
authors = ["Michael Hoang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
num-integer = "0.1"
num-traits = "0.2"
